server:
  port: 800
  # zipkin/sleuth链路跟踪

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样值介于0到1之间,1表示全部采集
      probability: 1
#入驻注册中心
eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 单机版
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order-80
    prefer-ip-address: true
