#端口
server:
  port: 8001
#服务名称
spring:
  application:
    name: cloud-payment-service
  # zipkin/sleuth链路跟踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样值介于0到1之间,1表示全部采集
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
#入驻注册中心
eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # 集群版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    #单机版
     defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #eureka向服务端发送心跳的时间
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为s，超时将删除服务
    lease-expiration-duration-in-seconds: 2
#type-aliases-package
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #别名
  type-aliases-package: com.xiaohe.springcloud.entities
  #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl